name: CI  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
      
    steps:  
    - uses: actions/checkout@v3  
      
    - name: Install dependencies  
      run: |  
        sudo apt-get update  
        sudo apt-get install -y build-essential cmake libgl1-mesa-dev freeglut3-dev  
      
    - name: Configure CMake  
      run: |  
        mkdir -p build  
        cd build  
        cmake ..  
      
    - name: Build  
      run: |  
        cd build  
        make
